start content for issue #08
NixOS/nixos-weekly pull request #38
Opened 2017-05-08 20:58 UTC by badi

Hi. I took the liberty of starting the content for issue 8 with the NixCon 2017.
I wasn't sure what your process for choosing the description was, so I picked one to get things started :)

2017-05-09 10:33 UTC, garbas commented
@badi this is exactly how it should be done. i love the quote :)

I guess sometime next week it would be nice to finish 08 weekly issue.

@badi would you like to be the editor of this one? I would of-course help you collect the news etc ... but the selection of words in intro and outro is up to you :)

2017-05-09 14:46 UTC, badi commented
> @badi this is exactly how it should be done. i love the quote :)
Awesome :)

> @badi would you like to be the editor of this one? I would of-course help you collect the news etc ... but the selection of words in intro and outro is up to you :)
Sure. I'm happy collecting topics in this thread if that works for everyone.

> I guess sometime next week it would be nice to finish 08 weekly issue.
I'll set the date for May 19 then.

2017-05-09 15:16 UTC, badi commented
NixOps meetup https://www.meetup.com/Munich-NixOS-Meetup/events/239835348/

2017-05-10 01:25 UTC, grahamc commented
Wiki was shut down: https://github.com/NixOS/nixos-org-configurations/pull/30 replaced with: https://nixos.org/nixos/wiki.html

2017-05-10 06:39 UTC, CMCDragonkai commented
This is our blog post on how to make your NixOS configuration reproducible. (as in instead of using nix-channels, using the nixpkgs git repositories)

2017-05-10 07:01 UTC, Mic92 commented
- A new community wiki was created:
-  https://github.com/nixos-users/wiki/wiki
-  It is editable by every GitHub user.

2017-05-10 08:47 UTC, domenkozar commented
@CMCDragonkai nice. I've documented this also in http://nix-cookbook.readthedocs.io/en/latest/faq.html#how-to-pin-nixpkgs-to-a-specific-commit-branch and header of http://howoldis.herokuapp.com/

2017-05-10 14:14 UTC, Profpatsch commented
Nix has a very thankful community: [1.9% of IRC messages contain “thank”](https://twitter.com/Profpatsch/status/862303014601846784) or over the last year [even 2.4%](https://twitter.com/grhmc/status/862304182002479105).

I might analyse that some more and turn it into a blog post for fun. ;)

2017-05-11 12:35 UTC, olejorgenb commented
Not so much news, but I think including a couple tips/tricks/small scripts could make sense.

Some suggestions: (including some shameless plugs :))

**[pnix-shell.sh](https://gist.github.com/aherrmann/51b56283f9ed5853747908fbab907316)**

Creates gc-roots for all dependencies of a shell.nix file ([ML discussion](http://lists.science.uu.nl/pipermail/nix-dev/2016-November/022173.html))

**[nix-package-search](https://www.reddit.com/r/NixOS/comments/5yxt45/simple_nix_package_search/)**

Small script that creates a cache of `nix-env -qa --json` use that for faster search. I've created a [gist](https://gist.github.com/olejorgenb/0c3bafa3c7b63d1a2f83ee13582de7b9) and slightly modified it. (increase cache invalidation time, add free-memory check, and only search `<nixpkgs>`)

**[Pretty complete zsh completions for the nix-* tools](https://github.com/spwhitt/nix-zsh-completions)**

In addition to options, attribute paths (`nix-env -iA`, `nix-env -i --file local.nix -A`,  `nix-shell '<nixpkgs>' -A`, `nix-shell -p`, etc.), `nix-shell '<ni>'` and `nix-env -e` is completed.

**NIX_AUTO_RUN=1**

Probably not very well known - maybe not something most people want on, but a cool feature none-the-less.

2017-05-11 16:04 UTC, domenkozar commented
We are hiring: https://twitter.com/iElectric/status/862589123479130112

2017-05-11 19:45 UTC, badi commented
Use NixOS fire macOS timemachine backups
http://grahamc.com/blog/timemachine-backups-linux-nixos

2017-05-11 20:13 UTC, telent commented
Example of building Maven projects (java) as Nix derivations - 

* https://mailman.science.uu.nl/pipermail/nix-dev/2017-May/023677.html
* https://ww.telent.net/2017/5/10/building_maven_packages_with_nix

Written by a non-expert, feedback welcome

2017-05-12 05:07 UTC, CMCDragonkai commented
@olejorgenb I had to look what you were talking about, here's the quote from ML:

> NIX_AUTO_RUN=1 means the program will be run via nix-shell. (The
grabage collector may remove it on the next GC run.)
> 
> NIX_AUTO_INSTALL=1 means the program will be installed with nix-env
and then run from your normal shell. (It won't be automatically
garbage collected.)
> https://mailman.science.uu.nl/pipermail/nix-dev/2017-May/023569.html

That's really cool functionality, but I'm not sure I'd want to enable it. (I would prefer a confirmation prompt).

2017-05-14 12:07 UTC, badi commented
"My Journey into Nix" blog post via lobste.rs
https://lobste.rs/s/nw8luo/my_journey_into_nix

2017-05-15 02:22 UTC, grahamc commented
DistroWatch posted a nice review of NixOS: https://distrowatch.com/weekly.php?issue=20170515

2017-05-17 12:06 UTC, Profpatsch requested changes

2017-05-17 12:06 UTC, Profpatsch commented on content/2017/08-not-all-those-who-wander-are-lost.rst
> +:date: 2017-05-10
That’s 7 days ago?

2017-05-17 12:06 UTC, Profpatsch commented on content/2017/08-not-all-those-who-wander-are-lost.rst
> +- `NixCon 2017`_ October 28-31, Munich.
The nixcon should probably be featured a lot more prominent, since it’s going to be the biggest community event this year.

2017-05-17 13:59 UTC, ocharles commented
We (CircuitHub) are hiring a Haskell engineer, but we use NixOS heavily for dev and deployments. Is that suitable here? https://circuithub.com/careers/haskellers#block-27f97af4532dee9c4127

2017-05-17 14:07 UTC, garbas commented on content/2017/08-not-all-those-who-wander-are-lost.rst
> +- `NixCon 2017`_ October 28-31, Munich.
:+1: to @Profpatsch  suggestion. I would mention NixCon right after description

2017-05-17 15:03 UTC, badi commented on content/2017/08-not-all-those-who-wander-are-lost.rst
> +:date: 2017-05-10
Whoops, fixed.
I was working around my unfamiliarity with pelican. Switching to `:status: draft` seems the better approach.

2017-05-17 15:04 UTC, badi commented on content/2017/08-not-all-those-who-wander-are-lost.rst
> +- `NixCon 2017`_ October 28-31, Munich.
I moved it back up into the News section and mentioned it in the introduction.

2017-05-17 15:04 UTC, badi commented
> We (CircuitHub) are hiring a Haskell engineer, but we use NixOS heavily for dev and deployments. Is that suitable here? https://circuithub.com/careers/haskellers#block-27f97af4532dee9c4127

I added it

2017-05-17 15:12 UTC, badi commented
@garbas I'll be traveling all of Friday so I'll plan to flip the status from draft to published evening of the 18th (I'll be on UTC -7)

2017-05-18 14:53 UTC, garbas commented
@badi sounds good... i'll send out email this evening or tomorrow morning

2017-05-18 15:00 UTC, badi commented
@garbas @Profpatsch if there are no further changes requested this should be good to merge.

2017-05-18 15:07 UTC, garbas commented
@badi I've added you to the collaborators list. once you accepted the invitation you shouuld be able to merged it yourself

2017-05-18 15:07 UTC, garbas commented
/me click the wrong button :)

2017-05-18 22:45 UTC, garbas commented
maybe we can squeeze in also this blogpost which just poped up on twitter
https://medium.com/@GauthierPLM/falling-in-love-with-nixos-36db4e50171e

2017-05-19 05:46 UTC, merged

2017-05-19 06:06 UTC, garbas commented
@badi 👍 merged to production and send out emails